version: '3'

services: 
    database:
        image: postgres:9.6
        ports:
            - 5432:5432
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
    rails_app:
        build: 
            context: .
            dockerfile: test.Dockerfile
        ports: 
            - "3000:3000"
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        depends_on:
            - database
