version: '3'

services:
    docker_in_docker:
        image: 'docker:dind'
        privileged: true
        ports: 
            - '2376:2376'
        links:
            - socat
        volumes:
            - jenkins-data:/var/jenkins_home
    socat:
        image: bpack/socat
        command: TCP4-LISTEN:2376,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "2376"
    jenkins:
        image: 'jenkinsci/blueocean'
        privileged: true
        environment:
            - DOCKER_HOST=tcp://socat:2376
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes: 
            - jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on: 
            - docker_in_docker
            - socat
    database:
        image: postgres:9.6
        ports:
            - 5432:5432
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
    rails_app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        depends_on:
            - database
volumes:
    jenkins-data: