version: '3'

services:
    docker_in_docker:
        image: 'docker:dind'
        privileged: true
        ports: 
            - '2375:2375'
        links:
            - socat
        volumes:
            - jenkins-data:/var/jenkins_home
            # - /var/run/docker.sock:/var/run/docker.sock
    socat:
        image: bpack/socat
        command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "2375"
    jenkins:
        image: 'jenkinsci/blueocean'
        privileged: true
        environment:
            - DOCKER_HOST=tcp://socat:2375
        links:
            - socat
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes: 
            - jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on: 
            - docker_in_docker
            - socat
    database:
        image: postgres:9.6
        ports:
            - 5432:5432
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
    rails_app:
        environment:
            - DOCKER_HOST=tcp://socat:2375
        build: 
            context: .
            dockerfile: test.Dockerfile
        ports: 
            - "3000:3000"
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - database
volumes:
    jenkins-data: