version: '3'

services:
    docker_in_docker:
        image: 'docker:dind'
        privileged: true
        ports: 
            - '2376:2376'
        networks:
            - 'jenkins_docker'
        links:
            - socat
        volumes:
            - jenkins-data:/var/jenkins_home
    socat:
        image: bpack/socat
        command: TCP4-LISTEN:2376,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
        networks:
            - 'jenkins_docker'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "2376"
    jenkins:
        image: 'jenkinsci/blueocean'
        privileged: true
        environment:
            - DOCKER_HOST=tcp://docker:2376
        ports:
            - '8080:8080'
            - '50000:50000'
        networks:
            - 'jenkins_docker'
        volumes: 
            - jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on: 
            - docker_in_docker
            - socat
networks:
    jenkins_docker:
volumes:
    jenkins-data: